# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log_in',
            fields=[
                ('phoneNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('timeAccess', models.DateTimeField()),
            ],
        ),
    ]
