# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibm', '0004_auto_20160317_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_in',
            old_name='phoneNumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='log_in',
            old_name='timeAccess',
            new_name='timeaccess',
        ),
        migrations.RenameField(
            model_name='log_in',
            old_name='userName',
            new_name='username',
        ),
    ]
