# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibm', '0006_auto_20160412_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_in',
            name='password2',
        ),
    ]
