# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ibm', '0007_remove_log_in_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_in',
            name='securitycode',
            field=models.CharField(default=datetime.datetime(2016, 4, 12, 10, 21, 43, 943737, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
