# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ibm', '0008_log_in_securitycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_in',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
