# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibm', '0012_remove_log_in_securitycode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_in',
            old_name='testcasePass',
            new_name='testcasepass',
        ),
    ]
