# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibm', '0002_auto_20160312_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_in',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=120)),
                ('userName', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('timeAccess', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Log_in1',
        ),
    ]
