# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibm', '0003_auto_20160312_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_in',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
