# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibm', '0005_auto_20160317_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_in',
            old_name='password',
            new_name='password2',
        ),
    ]
