# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 14:26
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ibm', '0010_remove_log_in_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_in',
            name='testcasePass',
            field=fernet_fields.fields.EncryptedCharField(max_length=32, null=True),
        ),
    ]
