# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibm', '0011_log_in_testcasepass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_in',
            name='securitycode',
        ),
    ]
