# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'EffortlessAndSecureBanking' do
pod 'Alamofire'
pod 'SwiftyJSON'
end

target 'EffortlessAndSecureBankingTests' do

end

target 'EffortlessAndSecureBankingUITests' do

end

